# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 138b3304e9221ea7a8b3b2fc88ca5663565fc1c0d1af5cb87b8556449bf0a793624e852e373782eecc7017c66b2a9376185524d9c4e06153d78e35057b4919eb

test:
  secret_key_base: 7af9d50e7ae599f3b0236e7969aacde936d4a31358121099a1ad3da82ceb894d7c6a4d8c86a97e4dc6baab6bd7d473bc8dd0f9525a0531da3f61d70b19ae84d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
